# Generated by Django 4.2 on 2023-07-04 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 7, 52, 27, 282376)),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 7, 52, 27, 282376)),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 7, 52, 27, 282376)),
        ),
    ]
