# Generated by Django 4.2 on 2023-07-04 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_alter_order_created_alter_orderline_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 16, 6, 54, 754668)),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 16, 6, 54, 754668)),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 16, 6, 54, 754668)),
        ),
    ]
