# Generated by Django 4.2 on 2023-07-04 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_order_total_cost_alter_order_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 16, 30, 50, 671580)),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 16, 30, 50, 671580)),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 16, 30, 50, 671580)),
        ),
    ]
